# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1daa102ef62011ca91ab3b921e50f3704fee77f1c3abc13e4116990f9577be67ca4d491f6322016e29c1c1835e9f9e65a79feb63725304961aa811773420dbf8

test:
  secret_key_base: 6c4b46f140108b3e6e3a851d5d7ab1996708d84e6e0231c0f16eb9ed07ffaf457f5ef8e9c6d9b8323ce4113fa519a9f7f77df0a11635e8522074748269067c51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
